### ISSUE TITLE
dockerized deployment

### ISSUE THREAD

**Issue by alee** [comses/catalog#56]
using docker-compose to separate db, solr, django containers

**Comment by alee** [comment]
Issues with solr 6 and django haystack, probably an issue with the schema.xml registered with the solr core.
```
ERROR 2016-08-11 04:57:03,144 [pysolr|_send_request:385] Solr responded with an error (HTTP 400): [Reason: Invalid Date in Date Math String:'2016-06-09T08:47:00.381495+00:00Z']  │············································
Failed to add documents to Solr: Solr responded with an error (HTTP 400): [Reason: Invalid Date in Date Math String:'2016-06-09T08:47:00.381495+00:00Z']                          │············································
Traceback (most recent call last):                                                                                                                                                │············································
  File "/usr/local/lib/python3.5/site-packages/haystack/backends/solr_backend.py", line 72, in update                                                                             │············································
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())                                                                                                           │············································
  File "/usr/local/lib/python3.5/site-packages/pysolr.py", line 875, in add                                                                                                       │············································
    overwrite=overwrite, handler=handler)                                                                                                                                         │············································
  File "/usr/local/lib/python3.5/site-packages/pysolr.py", line 471, in _update                                                                                                   │············································
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})                                                                                 │············································
  File "/usr/local/lib/python3.5/site-packages/pysolr.py", line 386, in _send_request                                                                                             │············································
    raise SolrError(error_message % (resp.status_code, solr_message))                                                                                                             │············································
pysolr.SolrError: Solr responded with an error (HTTP 400): [Reason: Invalid Date in Date Math String:'2016-06-09T08:47:00.381495+00:00Z']                                         │············································
DEBUG 2016-08-11 04:57:03,424 [raven.contrib.django.client.DjangoClient|send_remote:669] Sending message of length 2772 to https://sentry.commons.asu.edu/api/4/store/            │············································
ERROR 2016-08-11 04:57:03,387 [haystack|update:77] Failed to add documents to Solr: Solr responded with an error (HTTP 400): [Reason: Invalid Date in Date Math String:'2016-06-09│············································
T08:47:00.381495+00:00Z']
```
